package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Assuresociale generated by hbm2java
 */
@Entity
@Table(name = "assuresociale", catalog = "app_cnam")
public class Assuresociale implements java.io.Serializable {

	private int matriculeAssure;
	private Filiere filiere;
	private int nbrBeneficiaire;
	private String caisseOriginale;
	private Set<Beneficiaire> beneficiaires = new HashSet<Beneficiaire>(0);
	private Set<Plafons> plafonses = new HashSet<Plafons>(0);

	public Assuresociale() {
		filiere = new Filiere();
	}

	public Assuresociale(int matriculeAssure, Filiere filiere, int nbrBeneficiaire, String caisseOriginale) {
		this.matriculeAssure = matriculeAssure;
		this.filiere = filiere;
		this.nbrBeneficiaire = nbrBeneficiaire;
		this.caisseOriginale = caisseOriginale;
	}

	public Assuresociale(int matriculeAssure, Filiere filiere, int nbrBeneficiaire, String caisseOriginale,
			Set<Beneficiaire> beneficiaires, Set<Plafons> plafonses) {
		this.matriculeAssure = matriculeAssure;
		this.filiere = filiere;
		this.nbrBeneficiaire = nbrBeneficiaire;
		this.caisseOriginale = caisseOriginale;
		this.beneficiaires = beneficiaires;
		this.plafonses = plafonses;
	}

	@Id

	@Column(name = "matriculeAssure", unique = true, nullable = false)
	public int getMatriculeAssure() {
		return this.matriculeAssure;
	}

	public void setMatriculeAssure(int matriculeAssure) {
		this.matriculeAssure = matriculeAssure;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codFiliere", nullable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@Column(name = "nbrBeneficiaire", nullable = false)
	public int getNbrBeneficiaire() {
		return this.nbrBeneficiaire;
	}

	public void setNbrBeneficiaire(int nbrBeneficiaire) {
		this.nbrBeneficiaire = nbrBeneficiaire;
	}

	@Column(name = "caisse_Originale", nullable = false, length = 200)
	public String getCaisseOriginale() {
		return this.caisseOriginale;
	}

	public void setCaisseOriginale(String caisseOriginale) {
		this.caisseOriginale = caisseOriginale;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assuresociale")
	public Set<Beneficiaire> getBeneficiaires() {
		return this.beneficiaires;
	}

	public void setBeneficiaires(Set<Beneficiaire> beneficiaires) {
		this.beneficiaires = beneficiaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assuresociale")
	public Set<Plafons> getPlafonses() {
		return this.plafonses;
	}

	public void setPlafonses(Set<Plafons> plafonses) {
		this.plafonses = plafonses;
	}

}
