package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bsacte generated by hbm2java
 */
@Entity
@Table(name = "bsacte", catalog = "app_cnam")
public class Bsacte implements java.io.Serializable {

	private int codActe;
	private Bulletindesoin bulletindesoin;
	private double montantDepenseActe;
	private Date annee;
	private int nombreActe;
	

	public Bsacte() {
		
		bulletindesoin=new Bulletindesoin();
		
		
	}

	public Bsacte(int codActe, Bulletindesoin bulletindesoin, double montantDepenseActe, Date annee, int nombreActe) {
		this.codActe = codActe;
		this.bulletindesoin = bulletindesoin;
		this.montantDepenseActe = montantDepenseActe;
		this.annee = annee;
		this.nombreActe = nombreActe;
	}

	@Id

	@Column(name = "codActe", unique = true, nullable = false)
	public int getCodActe() {
		return this.codActe;
	}

	public void setCodActe(int codActe) {
		this.codActe = codActe;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codBdeSoin", nullable = false)
	public Bulletindesoin getBulletindesoin() {
		return this.bulletindesoin;
	}

	public void setBulletindesoin(Bulletindesoin bulletindesoin) {
		this.bulletindesoin = bulletindesoin;
	}

	@Column(name = "montantDepenseActe", nullable = false, precision = 22, scale = 0)
	public double getMontantDepenseActe() {
		return this.montantDepenseActe;
	}

	public void setMontantDepenseActe(double montantDepenseActe) {
		this.montantDepenseActe = montantDepenseActe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "annee", nullable = false, length = 10)
	public Date getAnnee() {
		return this.annee;
	}

	public void setAnnee(Date annee) {
		this.annee = annee;
	}

	@Column(name = "nombreActe", nullable = false)
	public int getNombreActe() {
		return this.nombreActe;
	}

	public void setNombreActe(int nombreActe) {
		this.nombreActe = nombreActe;
	}

}
