package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bsmedicament generated by hbm2java
 */
@Entity
@Table(name = "bsmedicament", catalog = "app_cnam")
public class Bsmedicament implements java.io.Serializable {

	private int numSeq;
	private Bulletindesoin bulletindesoin;
	private double montantDepenseOrdonnance;
	private int annee;
	private int quantite;

	public Bsmedicament() {
		bulletindesoin = new Bulletindesoin();
	}

	public Bsmedicament(int numSeq, Bulletindesoin bulletindesoin, double montantDepenseOrdonnance, int annee,
			int quantite) {
		this.numSeq = numSeq;
		this.bulletindesoin = bulletindesoin;
		this.montantDepenseOrdonnance = montantDepenseOrdonnance;
		this.annee = annee;
		this.quantite = quantite;
	}

	@Id

	@Column(name = "numSeq", unique = true, nullable = false)
	public int getNumSeq() {
		return this.numSeq;
	}

	public void setNumSeq(int numSeq) {
		this.numSeq = numSeq;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codBdeSoin", nullable = false)
	public Bulletindesoin getBulletindesoin() {
		return this.bulletindesoin;
	}

	public void setBulletindesoin(Bulletindesoin bulletindesoin) {
		this.bulletindesoin = bulletindesoin;
	}

	@Column(name = "montantDepenseOrdonnance", nullable = false, precision = 22, scale = 0)
	public double getMontantDepenseOrdonnance() {
		return this.montantDepenseOrdonnance;
	}

	public void setMontantDepenseOrdonnance(double montantDepenseOrdonnance) {
		this.montantDepenseOrdonnance = montantDepenseOrdonnance;
	}

	@Column(name = "annee", nullable = false)
	public int getAnnee() {
		return this.annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	@Column(name = "quantite", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

}
