package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cnams generated by hbm2java
 */
@Entity
@Table(name = "cnams", catalog = "app_cnam")
public class Cnams implements java.io.Serializable {

	private Integer id;
	private float attitude;
	private float longitude;
	private String nom;

	public Cnams() {
	}

	public Cnams(float attitude, float longitude, String nom) {
		this.attitude = attitude;
		this.longitude = longitude;
		this.nom = nom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "attitude", nullable = false, precision = 12, scale = 0)
	public float getAttitude() {
		return this.attitude;
	}

	public void setAttitude(float attitude) {
		this.attitude = attitude;
	}

	@Column(name = "longitude", nullable = false, precision = 12, scale = 0)
	public float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(float longitude) {
		this.longitude = longitude;
	}

	@Column(name = "nom", nullable = false, length = 500)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
