package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Convention generated by hbm2java
 */
@Entity
@Table(name = "convention", catalog = "app_cnam")
public class Convention implements java.io.Serializable {

	private int codConv;
	private String libelle;
	private Set<Prestataire> prestataires = new HashSet<Prestataire>(0);

	public Convention() {
	}

	public Convention(int codConv, String libelle) {
		this.codConv = codConv;
		this.libelle = libelle;
	}

	public Convention(int codConv, String libelle, Set<Prestataire> prestataires) {
		this.codConv = codConv;
		this.libelle = libelle;
		this.prestataires = prestataires;
	}

	@Id

	@Column(name = "codConv", unique = true, nullable = false)
	public int getCodConv() {
		return this.codConv;
	}

	public void setCodConv(int codConv) {
		this.codConv = codConv;
	}

	@Column(name = "libelle", nullable = false, length = 500)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "convention")
	public Set<Prestataire> getPrestataires() {
		return this.prestataires;
	}

	public void setPrestataires(Set<Prestataire> prestataires) {
		this.prestataires = prestataires;
	}

}
