package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Decision generated by hbm2java
 */
@Entity
@Table(name = "decision", catalog = "app_cnam")
public class Decision implements java.io.Serializable {

	private int codDecision;
	private Priseencharge priseencharge;
	private String libelle;

	public Decision() {
		priseencharge = new Priseencharge();
	}

	public Decision(int codDecision, Priseencharge priseencharge, String libelle) {
		this.codDecision = codDecision;
		this.priseencharge = priseencharge;
		this.libelle = libelle;
	}

	@Id

	@Column(name = "codDecision", unique = true, nullable = false)
	public int getCodDecision() {
		return this.codDecision;
	}

	public void setCodDecision(int codDecision) {
		this.codDecision = codDecision;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codDpe", nullable = false)
	public Priseencharge getPriseencharge() {
		return this.priseencharge;
	}

	public void setPriseencharge(Priseencharge priseencharge) {
		this.priseencharge = priseencharge;
	}

	@Column(name = "libelle", nullable = false, length = 500)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
