package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "app_cnam")
public class Facture implements java.io.Serializable {

	private int referFacture;
	private Prestataire prestataire;
	private Priseencharge priseencharge;
	private double montantFacture;
	private int montantPaye;
	private Date dateDepot;
	private Date dateFacture;
	private Date dateVirement;

	public Facture() {
		prestataire = new Prestataire();
		priseencharge = new Priseencharge();
	}

	public Facture(int referFacture, Prestataire prestataire, Priseencharge priseencharge, double montantFacture,
			int montantPaye, Date dateDepot, Date dateFacture, Date dateVirement) {
		this.referFacture = referFacture;
		this.prestataire = prestataire;
		this.priseencharge = priseencharge;
		this.montantFacture = montantFacture;
		this.montantPaye = montantPaye;
		this.dateDepot = dateDepot;
		this.dateFacture = dateFacture;
		this.dateVirement = dateVirement;
	}

	@Id

	@Column(name = "referFacture", unique = true, nullable = false)
	public int getReferFacture() {
		return this.referFacture;
	}

	public void setReferFacture(int referFacture) {
		this.referFacture = referFacture;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "matriculePrestataire", nullable = false)
	public Prestataire getPrestataire() {
		return this.prestataire;
	}

	public void setPrestataire(Prestataire prestataire) {
		this.prestataire = prestataire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codDpe", nullable = false)
	public Priseencharge getPriseencharge() {
		return this.priseencharge;
	}

	public void setPriseencharge(Priseencharge priseencharge) {
		this.priseencharge = priseencharge;
	}

	@Column(name = "MontantFacture", nullable = false, precision = 22, scale = 0)
	public double getMontantFacture() {
		return this.montantFacture;
	}

	public void setMontantFacture(double montantFacture) {
		this.montantFacture = montantFacture;
	}

	@Column(name = "MontantPaye", nullable = false)
	public int getMontantPaye() {
		return this.montantPaye;
	}

	public void setMontantPaye(int montantPaye) {
		this.montantPaye = montantPaye;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDepot", nullable = false, length = 10)
	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateFacture", nullable = false, length = 10)
	public Date getDateFacture() {
		return this.dateFacture;
	}

	public void setDateFacture(Date dateFacture) {
		this.dateFacture = dateFacture;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateVirement", nullable = false, length = 10)
	public Date getDateVirement() {
		return this.dateVirement;
	}

	public void setDateVirement(Date dateVirement) {
		this.dateVirement = dateVirement;
	}

}
