package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "app_cnam")
public class Filiere implements java.io.Serializable {

	private int codFiliere;
	private String annee;
	private String libelle;
	private Set<Assuresociale> assuresociales = new HashSet<Assuresociale>(0);

	public Filiere() {
	}

	public Filiere(int codFiliere, String annee, String libelle) {
		this.codFiliere = codFiliere;
		this.annee = annee;
		this.libelle = libelle;
	}

	public Filiere(int codFiliere, String annee, String libelle, Set<Assuresociale> assuresociales) {
		this.codFiliere = codFiliere;
		this.annee = annee;
		this.libelle = libelle;
		this.assuresociales = assuresociales;
	}

	@Id

	@Column(name = "codFiliere", unique = true, nullable = false)
	public int getCodFiliere() {
		return this.codFiliere;
	}

	public void setCodFiliere(int codFiliere) {
		this.codFiliere = codFiliere;
	}

	@Column(name = "annee", nullable = false, length = 100)
	public String getAnnee() {
		return this.annee;
	}

	public void setAnnee(String annee) {
		this.annee = annee;
	}

	@Column(name = "libelle", nullable = false, length = 500)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiere")
	public Set<Assuresociale> getAssuresociales() {
		return this.assuresociales;
	}

	public void setAssuresociales(Set<Assuresociale> assuresociales) {
		this.assuresociales = assuresociales;
	}

}
