package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prestation generated by hbm2java
 */
@Entity
@Table(name = "prestation", catalog = "app_cnam")
public class Prestation implements java.io.Serializable {

	private int codPrestation;
	private Priseencharge priseencharge;
	private String libelle;

	public Prestation() {
		priseencharge = new Priseencharge();
	}

	public Prestation(int codPrestation, Priseencharge priseencharge, String libelle) {
		this.codPrestation = codPrestation;
		this.priseencharge = priseencharge;
		this.libelle = libelle;
	}

	@Id

	@Column(name = "codPrestation", unique = true, nullable = false)
	public int getCodPrestation() {
		return this.codPrestation;
	}

	public void setCodPrestation(int codPrestation) {
		this.codPrestation = codPrestation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codDep", nullable = false)
	public Priseencharge getPriseencharge() {
		return this.priseencharge;
	}

	public void setPriseencharge(Priseencharge priseencharge) {
		this.priseencharge = priseencharge;
	}

	@Column(name = "libelle", nullable = false, length = 300)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
