package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prestataire generated by hbm2java
 */
@Entity
@Table(name = "prestataire", catalog = "app_cnam")
public class Prestataire implements java.io.Serializable {

	private int matriculePrestataire;
	private Convention convention;
	private String typePrestataire;
	private String maisonSociale;
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Prestataire() {
		convention=new Convention ();
	}

	public Prestataire(int matriculePrestataire, Convention convention, String typePrestataire, String maisonSociale) {
		this.matriculePrestataire = matriculePrestataire;
		this.convention = convention;
		this.typePrestataire = typePrestataire;
		this.maisonSociale = maisonSociale;
	}

	public Prestataire(int matriculePrestataire, Convention convention, String typePrestataire, String maisonSociale,
			Set<Facture> factures) {
		this.matriculePrestataire = matriculePrestataire;
		this.convention = convention;
		this.typePrestataire = typePrestataire;
		this.maisonSociale = maisonSociale;
		this.factures = factures;
	}

	@Id

	@Column(name = "matriculePrestataire", unique = true, nullable = false)
	public int getMatriculePrestataire() {
		return this.matriculePrestataire;
	}

	public void setMatriculePrestataire(int matriculePrestataire) {
		this.matriculePrestataire = matriculePrestataire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codConv", nullable = false)
	public Convention getConvention() {
		return this.convention;
	}

	public void setConvention(Convention convention) {
		this.convention = convention;
	}

	@Column(name = "typePrestataire", nullable = false, length = 200)
	public String getTypePrestataire() {
		return this.typePrestataire;
	}

	public void setTypePrestataire(String typePrestataire) {
		this.typePrestataire = typePrestataire;
	}

	@Column(name = "maisonSociale", nullable = false, length = 200)
	public String getMaisonSociale() {
		return this.maisonSociale;
	}

	public void setMaisonSociale(String maisonSociale) {
		this.maisonSociale = maisonSociale;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestataire")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
