package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Priseencharge generated by hbm2java
 */
@Entity
@Table(name = "priseencharge", catalog = "app_cnam")
public class Priseencharge implements java.io.Serializable {

	private int codDpe;
	private Beneficiaire beneficiaire;
	private Centrecnam centrecnam;
	private Date dateDepot;
	private Date dateEdition;
	private String etatPre;
	private Set<Prestation> prestations = new HashSet<Prestation>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);
	private Set<Decision> decisions = new HashSet<Decision>(0);

	public Priseencharge() {
		beneficiaire= new Beneficiaire();
		centrecnam=new Centrecnam();
	}

	public Priseencharge(int codDpe, Beneficiaire beneficiaire, Centrecnam centrecnam, Date dateDepot, Date dateEdition,
			String etatPre) {
		this.codDpe = codDpe;
		this.beneficiaire = beneficiaire;
		this.centrecnam = centrecnam;
		this.dateDepot = dateDepot;
		this.dateEdition = dateEdition;
		this.etatPre = etatPre;
	}

	public Priseencharge(int codDpe, Beneficiaire beneficiaire, Centrecnam centrecnam, Date dateDepot, Date dateEdition,
			String etatPre, Set<Prestation> prestations, Set<Facture> factures, Set<Decision> decisions) {
		this.codDpe = codDpe;
		this.beneficiaire = beneficiaire;
		this.centrecnam = centrecnam;
		this.dateDepot = dateDepot;
		this.dateEdition = dateEdition;
		this.etatPre = etatPre;
		this.prestations = prestations;
		this.factures = factures;
		this.decisions = decisions;
	}

	@Id

	@Column(name = "codDpe", unique = true, nullable = false)
	public int getCodDpe() {
		return this.codDpe;
	}

	public void setCodDpe(int codDpe) {
		this.codDpe = codDpe;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codeBenef", nullable = false)
	public Beneficiaire getBeneficiaire() {
		return this.beneficiaire;
	}

	public void setBeneficiaire(Beneficiaire beneficiaire) {
		this.beneficiaire = beneficiaire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CodeCnam", nullable = false)
	public Centrecnam getCentrecnam() {
		return this.centrecnam;
	}

	public void setCentrecnam(Centrecnam centrecnam) {
		this.centrecnam = centrecnam;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDepot", nullable = false, length = 10)
	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateEdition", nullable = false, length = 10)
	public Date getDateEdition() {
		return this.dateEdition;
	}

	public void setDateEdition(Date dateEdition) {
		this.dateEdition = dateEdition;
	}

	@Column(name = "etatPRE", nullable = false, length = 200)
	public String getEtatPre() {
		return this.etatPre;
	}

	public void setEtatPre(String etatPre) {
		this.etatPre = etatPre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "priseencharge")
	public Set<Prestation> getPrestations() {
		return this.prestations;
	}

	public void setPrestations(Set<Prestation> prestations) {
		this.prestations = prestations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "priseencharge")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "priseencharge")
	public Set<Decision> getDecisions() {
		return this.decisions;
	}

	public void setDecisions(Set<Decision> decisions) {
		this.decisions = decisions;
	}

}
