package com.cnam.entity;
// Generated 20 avr. 2017 00:49:55 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "app_cnam")
public class Users implements java.io.Serializable {

	private String username;
	private Centrecnam centrecnam;
	private String password;
	private int enabled;
	private String role;

	public Users() {
		centrecnam= new Centrecnam();
	}

	public Users(String username, Centrecnam centrecnam, String password, int enabled, String role) {
		this.username = username;
		this.centrecnam = centrecnam;
		this.password = password;
		this.enabled = enabled;
		this.role = role;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CodeCnam", nullable = false)
	public Centrecnam getCentrecnam() {
		return this.centrecnam;
	}

	public void setCentrecnam(Centrecnam centrecnam) {
		this.centrecnam = centrecnam;
	}

	@Column(name = "password", nullable = false, length = 500)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "enabled", nullable = false)
	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	@Column(name = "role", nullable = false, length = 500)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
